name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/k8s-app:v1 .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/k8s-app:v1
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/k8s-app:v1